#!/bin/sh -e
envdir=$PWD/env
root=$(<env/TD_Root)
port=$(<env/TD_Innate_Port)
echo Starting from $root
cd $root
if [ -s $HOME/.rvm/scripts/rvm ]; then
  source $HOME/.rvm/scripts/rvm
  echo "Using RVM $(which rvm)"
  rvm use 1.9.2 2>&1
fi

exec chpst -e $envdir thin -R config.ru -p $port start 2>&1
